os: linux
dist: xenial
language: perl
perl:
  - "5.26"

addons:
  apt:
    packages:
      - ruby 
      - ruby-dev 
      - rubygems 
      - build-essential

branches:
  except:
    - /^latest$/

before_install:
  - mkdir /tmp/out/
  - if [ -z ${TRAVIS_TAG} ] || [ ${TRAVIS_TAG} == *-* ]; then export VERSION=latest; else export VERSION=${TRAVIS_TAG}; fi
  - echo ${TRAVIS_TAG}
  - echo ${VERSION}

install:
  - gem install --no-ri --no-rdoc fpm
script:
  - sed "s/\"latest\"/\"${VERSION}\"/" ercole-agent > /tmp/ercole-agent
  - cp /tmp/ercole-agent ercole-agent
  - tar -C . -cvzf /tmp/out/ercole-agent-aix-${VERSION}.tar.gz .
  - fpm -n ercole-agent -s dir -x ".git" -x ".travis.yml" -x "README.md" -x "LICENSE" -t rpm --prefix /opt/ercole-agent-aix -a all --rpm-os aix6.1 --package /tmp/out --version ${VERSION} --name ercole-agent-aix .
  - mv /tmp/out/ercole-agent-aix-${VERSION}-1.noarch.rpm /tmp/out/ercole-agent-aix-${VERSION}-1.noarch.rpm

before_deploy:
  - if [[ ${VERSION} == "latest" ]]; then git tag -f latest; fi
  - if [[ ${VERSION} == "latest" ]]; then git remote add gh https://simonerota:${GITHUB_RELEASE_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git; fi
  - if [[ ${VERSION} == "latest" ]]; then git push gh latest || true; fi
  - if [[ ${VERSION} == "latest" ]]; then git push -f gh latest; fi
  - if [[ ${VERSION} == "latest" ]]; then git remote remove gh; fi

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file_glob: true
  file: /tmp/out/*
  skip_cleanup: true
  name: $VERSION
  overwrite: true
  on:
    all_branches: true
