os: linux
dist: xenial
language: perl
perl:
  - "5.26"

services:
  - docker

sudo: required

env:
  global:
    - PACKAGE_BUILD_IMAGE=sorintdev/rpmbuild-mugs:0.1
    - WORKSPACE=/build

matrix:
  include:
    - env: DIST=aix6.1

branches:
  except:
    - /^latest$/

before_install:
  - mkdir /tmp/out/
  - if [ -z ${TRAVIS_TAG} ] || [ ${TRAVIS_TAG} == *-* ]; then export VERSION=latest; else export VERSION=${TRAVIS_TAG}; fi
  - echo ${TRAVIS_TAG}
  - echo ${VERSION}
  - sudo docker pull ${PACKAGE_BUILD_IMAGE}

install:
  - sudo docker run -d --rm -it -e WORKSPACE="${WORKSPACE}" -e TRAVIS_REPO_SLUG="${TRAVIS_REPO_SLUG}" -e TRAVIS_BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}" -v $PWD:"${WORKSPACE}" --name package_builder ${PACKAGE_BUILD_IMAGE} /bin/cat

script:
  - sed "s/\"latest\"/\"${VERSION}\"/" ercole-agent > /tmp/ercole-agent
  - cp /tmp/ercole-agent ercole-agent
  - tar -C . -cvzf /tmp/out/ercole-agent-aix-${VERSION}.tar.gz .
  - docker exec -it package_builder /bin/sh -c "cd ${WORKSPACE} && fpm -n ercole-agent -s dir -x '*.git*' -x '*.travis.yml*' -x '*README.md*' -x '*LICENSE*' -t rpm -a all --rpm-os ${DIST} --version ${VERSION} --name ercole-agent-aix ".=/opt/ercole-agent-aix" package/aix/ercole-agent=/etc/rc.d/init.d/" 
  - mv ercole-agent-aix-${VERSION}-1.noarch.rpm /tmp/out/ercole-agent-aix-${VERSION}-1.${DIST}.noarch.rpm

before_deploy:
  - if [[ ${VERSION} == "latest" ]]; then git tag -f latest; fi
  - if [[ ${VERSION} == "latest" ]]; then git remote add gh https://simonerota:${GITHUB_RELEASE_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git; fi
  - if [[ ${VERSION} == "latest" ]]; then git push gh latest || true; fi
  - if [[ ${VERSION} == "latest" ]]; then git push -f gh latest; fi
  - if [[ ${VERSION} == "latest" ]]; then git remote remove gh; fi

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file_glob: true
  file: /tmp/out/*
  skip_cleanup: true
  name: $VERSION
  overwrite: true
  on:
    all_branches: true
